### ISSUE TITLE
Provision and Deploy FOLIO Instance

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinolio#15]
Provision a FOLIO `platform-core` environment to AWS EKS with two initial tenants, Stanford and Cornell.

**Comment by jgreben** [comment]
- [x] Fork https://github.com/folio-org/platform-core into https://github.com/LD4P/platform-core
- [x] Clone LD4P/platform-core locally and checkout the R2-2021 branch
- [x] Copy custom images for Sinopia into `tenant-assets` and modify `stripes.config.js`
- [x] Follow steps to install okapi, backend modules, and platform-core in k8s: https://github.com/sul-dlss/folio-k8s#readme
- [x]  Document steps to add additional tenants.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-k8s/pull/41
